# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47e793d43a351d7bbb3ba4f5bc033e96e6e74676b7776bd61d60b5bf91a24892efcde91d89aa25f3b4350ae3ef520b9f93d90808276889e5e075a6825c3236c2

test:
  secret_key_base: 3c62a5aa35e1760e35ea1943f7a2156c75a1779e36c9987c58c61f8848a2b0ba9a5a26ea499168116246f476457e4f7ae6dff723cc038bba1ca23e97d1a08b07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
