version: '3'
services:
  moon_mysql:
    image: mysql:5.7
    container_name: moon_mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: moon
    ports:
      - 127.0.0.1:$MOON_MYSQL_PORT:3306

  moon_files:
    image: httpd:latest
    volumes:
      - ./public_files:/usr/local/apache2/htdocs
    ports:
      - 127.0.0.1:3001:80
  #################### Base  ####################

  base: &base
    image: darthjee/moon
    volumes:
      - ./source:/home/app/app
    links:
      - moon_mysql:mysql
    env_file: .env


  base_build:
    <<: *base
    build:
      context: .
      dockerfile: Dockerfile.moon
    command: echo done

  #################### CONTAINERS ####################

  moon_app:
    <<: *base
    container_name: moon_app
    command: /bin/bash bin/server.sh
    depends_on: [base_build]
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - RAILS_ENV=development
      - MOON_MYSQL_PORT=3306

  moon_tests:
    <<: *base
    container_name: moon_tests
    command: /bin/bash bin/tests.sh
    depends_on: [base_build]
    environment:
      - RAILS_ENV=test

  moon_root:
    <<: *base
    user: root
    container_name: moon_root
    command: /bin/bash
    depends_on: [base_build]

  moon_production:
    env_file: .env.production
    container_name: moon_production
    image: darthjee/production_moon
    build:
      context: .
      dockerfile: Dockerfile.production_moon
