version: '3'
services:
  moon_postgres:
    image: postgres:9.5
    container_name: moon_postgres
    env_file: .env
    environment:
      POSTGRES_USER: moon
      POSTGRES_PASSWORD: moon
    ports:
      - 127.0.0.1:$MOON_POSTGRES_PORT:5432
  #################### Base  ####################

  base: &base
    image: darthjee/moon
    volumes:
      - ./source:/home/app/app
    links:
      - moon_postgres:postgres
    env_file: .env


  base_build:
    <<: *base
    build:
      context: .
      dockerfile: Dockerfile.moon
    command: echo done

  production_base_build:
    image: darthjee/production_moon
    env_file: .env
    environment:
      RAILS_ENV: production
    build:
      context: .
      dockerfile: Dockerfile.production_moon
    links:
      - moon_postgres:postgres
    command: echo done
  #################### CONTAINERS ####################

  moon_app:
    <<: *base
    container_name: moon_app
    command: /bin/bash bin/server.sh
    depends_on: [base_build]
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - RAILS_ENV=development
      - DR_MARIO_MYSQL_PORT=3306

  moon_tests:
    <<: *base
    container_name: moon_tests
    command: /bin/bash bin/tests.sh
    depends_on: [base_build]
    environment:
      - RAILS_ENV=test

  moon_root:
    <<: *base
    user: root
    container_name: moon_root
    command: /bin/bash
    depends_on: [base_build]

  moon_production:
    depends_on: [production_base_build, moon_postgres]
    container_name: moon_production
    image: darthjee/production_moon
    links:
      - moon_postgres:postgres
    env_file: .env
    environment:
      RAILS_ENV: production
