inherit_from: .rubocop_todo.yml

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/routes.rb'
    - 'db/schema.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'spec/**/*.rb'
