inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'db/**/*.rb'
    - 'spec/**/*_spec.rb'
    - 'spec/support/**/*.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/schema.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'

Layout/LineLength:
  Exclude:
    - 'bin/bundle'

Style/FetchEnvVar:
  Enabled: true
  Exclude:
    - 'bin/bundle'

Style/RedundantConstantBase:
  Enabled: true
  Exclude:
    - config/environments/production.rb

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true
  Exclude:
    - spec/**/*_spec.rb

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 7

RSpec/ExampleLength:
  Max: 8

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
